[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Prevent clickjacking attacks
    X-Frame-Options = "DENY"
    
    # Enable XSS protection (legacy browsers)
    X-XSS-Protection = "1; mode=block"
    
    # Control referrer information
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Restrict browser features
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Content Security Policy
    # This is a strict policy that allows only necessary resources
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://app.kit.com https://f.convertkit.com;
      style-src 'self' 'unsafe-inline';
      img-src 'self' data: https: blob:;
      font-src 'self' data:;
      connect-src 'self' https://zfuokpddfofaneazfrhf.supabase.co https://app.kit.com https://api.convertkit.com wss://zfuokpddfofaneazfrhf.supabase.co;
      frame-src https://savvycal.com;
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'self' https://app.kit.com;
      upgrade-insecure-requests;
    """

# Cache control for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Prevent caching of HTML files
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"