# Example GitHub Actions Workflow with Supabase Migrations
# This is a TEMPLATE - do not replace your existing workflows
# Instead, add the migration steps to your existing .github/workflows/ files

name: Example CI with Supabase Migrations
on: [push, pull_request]

jobs:
  test-with-migrations:
    name: Test with Database Migrations
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    # 🆕 NEW: Apply Supabase migrations before running tests
    # This ensures the database schema is up-to-date for tests
    - name: Apply Supabase migrations
      run: npm run migrate
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    # Continue with your existing steps
    - name: Run linter
      run: npm run lint

    - name: Run tests
      run: npm run test:run
      env:
        # Use the same Supabase URL for tests if needed
        VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

    - name: Build project
      run: npm run build
      env:
        VITE_SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        VITE_SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}

# INTEGRATION NOTES:
# 
# For your existing workflows, add this step after "Install dependencies":
#
# - name: Apply Supabase migrations
#   run: npm run migrate
#   env:
#     SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
#     SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
#
# Required secrets to add to your repository:
# - SUPABASE_URL: Your Supabase project URL
# - SUPABASE_SERVICE_ROLE_KEY: Service role key (NOT the anon key)
# - SUPABASE_ANON_KEY: Anon key for frontend (if needed for tests)