// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

import type { Database } from './types';

const SUPABASE_URL = "https://zfuokpddfofaneazfrhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmdW9rcGRkZm9mYW5lYXpmcmhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMDIyMzYsImV4cCI6MjA2NzU3ODIzNn0.G9k735ZoOmA-Oy8byioh8sfw0BmWO1xsJtthsMu6Bjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});