name: Generate Sitemap

on:
  push:
    branches: [ main, master ]
    paths:
      - 'src/pages/**'
      - 'src/content/**'
  workflow_dispatch:

jobs:
  generate-sitemap:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Generate sitemap
      run: npm run generate-sitemap
      
    - name: Commit sitemap
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add public/sitemap.xml
        git diff --staged --quiet || git commit -m "Update sitemap [skip ci]"
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}